name: 'Terraform State Management'

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Action to perform'
        required: true
        default: 'IMPORT'
        type: choice
        options:
        - IMPORT
        - UNLOCK
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
      resource_address:
        description: 'Terraform Address (Only for IMPORT)'
        required: false
        default: 'module.aks.azurerm_kubernetes_cluster.aks["aks-dev-001"]'
      resource_id_or_lock_id:
        description: 'Azure Resource ID (for IMPORT) or Lock ID (for UNLOCK)'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  terraform-action:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    defaults:
      run:
        working-directory: environments/${{ github.event.inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Az Login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Execute Action
      run: |
        if [ "${{ github.event.inputs.action_type }}" == "UNLOCK" ]; then
          echo "Unlocking state with ID: ${{ github.event.inputs.resource_id_or_lock_id }}"
          terraform force-unlock -force ${{ github.event.inputs.resource_id_or_lock_id }}
        else
          echo "Importing resource: ${{ github.event.inputs.resource_address }}"
          terraform import '${{ github.event.inputs.resource_address }}' '${{ github.event.inputs.resource_id_or_lock_id }}'
        fi
